--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CRIMINALS
--------------------------------------------------------

  CREATE TABLE "HR"."CRIMINALS" 
   (	"CRIMINAL_ID" NUMBER, 
	"CRIMINAL_NAME" VARCHAR2(20 BYTE), 
	"CRIMINAL_SURNAME" VARCHAR2(20 BYTE), 
	"DATE_OF_BIRTH" DATE, 
	"DNI" VARCHAR2(20 BYTE), 
	"CRIMINAL_RECORD" VARCHAR2(20 BYTE), 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SOCIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."SOCIOS_PK" ON "HR"."CRIMINALS" ("CRIMINAL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CRIMINALS
--------------------------------------------------------

  ALTER TABLE "HR"."CRIMINALS" ADD CONSTRAINT "SOCIOS_PK" PRIMARY KEY ("CRIMINAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."CRIMINALS" MODIFY ("CRIMINAL_RECORD" NOT NULL ENABLE);
  ALTER TABLE "HR"."CRIMINALS" MODIFY ("CRIMINAL_ID" NOT NULL ENABLE);
